### ISSUE TITLE
Using floating edit link causes plugin to call up start page

### ISSUE THREAD

**Issue by nosbig** [chang-zhao/dokuwiki-editonlink#5]
On both a customized and a fresh install of Dokuwiki with default settings, I have an issue with using the hover edit links provided by the plugin.

When I click on the edit link on any wiki link, the plugin edits the wiki start page, rather than the page targeted by the link.

This exhibits itself on both new pages which don't exist or pages which already exist.

**Comment by chang-zhao** [comment]
@nosbig, thank you for reporting!

Please update the plugin, the bug should be fixed now.

(I used this with nice URL rewriting, and removed '?' parameters which should be replaced with 'do=edit'; but I missed the use case with '?id='. Now it should be OK).
